default_platform(:android)

platform :android do
  desc "Build Android APK for Ionic/Capacitor project"
  lane :build_android do
    sh "npm install"
    sh "ionic build"
    sh "npx cap sync android"
    puts "✅ Project ready for Appflow remote build."
  end

  after_all do |lane|
    puts "Skipping clean-up to avoid errors."
  end

  error do |lane, exception|
    puts "❌ Fastlane encountered an error: #{exception}"
  end
end
